# Generated by Django 4.0.5 on 2022-06-20 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
