# Generated by Django 4.1 on 2022-08-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
